services:
  - type: web
    name: basharat-movies-hub
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn basharat.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: CLOUD_NAME
        value: your_cloud_name_here
      - key: API_KEY
        value: your_api_key_here
      - key: API_SECRET
        value: your_api_secret_here
