# Generated by Django 5.2.4 on 2025-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_poster_alter_playlist_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='udrop_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
