# Generated by Django 5.2.4 on 2025-09-25 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_installation_delete_installtracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('install_count', models.PositiveIntegerField(default=0)),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('last_action', models.CharField(default='install', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Installation',
        ),
    ]
