# Generated by Django 5.2.4 on 2025-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_udrop_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.TextField()),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
