# Generated by Django 5.2.4 on 2025-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_installtracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installtracker',
            old_name='installed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='installtracker',
            name='delete_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installtracker',
            name='install_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='installtracker',
            name='installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(blank=True, choices=[('install', 'Install'), ('delete', 'Delete')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='installtracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
