# Generated by Django 5.2.4 on 2025-09-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_installtracker_delete_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installtracker',
            name='device_info',
        ),
        migrations.AddField(
            model_name='installtracker',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='deleted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='install_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(choices=[('Install', 'Install'), ('Uninstall', 'Uninstall')], max_length=20),
        ),
    ]
