# Generated by Django 5.2.4 on 2025-09-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_installtracker_device_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installtracker',
            name='device_name',
        ),
    ]
