# Generated by Django 5.2.4 on 2025-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_installed_at_installtracker_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installtracker',
            name='device_info',
        ),
        migrations.AddField(
            model_name='installtracker',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installtracker',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installtracker',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
