# Generated by Django 5.2.4 on 2025-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_installtracker_device_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installtracker',
            name='client_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(choices=[('install', 'Install'), ('delete', 'Delete')], default='install', max_length=10),
        ),
    ]
