# Generated by Django 5.2.4 on 2025-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_installtracker_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='installtracker',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
