# Generated by Django 5.2.4 on 2025-08-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_installtracker_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installtracker',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(blank=True, choices=[('install', 'Install'), ('delete', 'Delete')], max_length=10, null=True),
        ),
    ]
