# Generated by Django 5.2.4 on 2025-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_installtracker_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installtracker',
            name='deleted_count',
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(blank=True, choices=[('Install', 'Install')], max_length=20, null=True),
        ),
    ]
