# Generated by Django 5.2.4 on 2025-08-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_installtracker_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installtracker',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='installtracker',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='installtracker',
            name='installed_at',
        ),
        migrations.AddField(
            model_name='installtracker',
            name='device_info',
            field=models.TextField(blank=True, default='Unknown Device', null=True),
        ),
    ]
