# Generated by Django 5.2.4 on 2025-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_installtracker_deleted_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installtracker',
            name='install_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(default='Install', max_length=20),
        ),
    ]
