# Generated by Django 5.2.4 on 2025-08-24 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_installtracker_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installtracker',
            old_name='delete_count',
            new_name='deleted_count',
        ),
        migrations.RemoveField(
            model_name='installtracker',
            name='installed',
        ),
        migrations.AddField(
            model_name='installtracker',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='installtracker',
            name='last_action',
            field=models.CharField(default='install', max_length=20),
        ),
    ]
