# Generated by Django 5.2.4 on 2025-08-27 04:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_playlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installtracker',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
