# Generated by Django 5.2.4 on 2025-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_installtracker_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installtracker',
            name='install_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
