# Generated by Django 5.2.4 on 2025-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_installtracker_install_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installtracker',
            name='install_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
