name: Send Email Report

on:
  schedule:
    # हर 5 दिन में 00:00 UTC पर चलेगा
    - cron: "0 0 */5 * *"

  workflow_dispatch: # मैनुअली भी चला सकते हो
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run refresh_links.py to send report email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python refresh_links.py
